### ISSUE TITLE
The details about Periodicity-Variant Augmentations

### ISSUE THREAD

**Issue by LuPaoPao** [YyzHarry/SimPer#1]
Thanks for your great work, I was wondering how you get different samples at different speeds?

I once augmented by cubic spline interpolation and found that the results were poor.

Looking forward to your reply

**Comment by YyzHarry** [comment]
The video frames are interpolated in the time domain with a continuous scale factor. We simply use off-the-shelf functions (e.g., `tfp.math.interp_regular_1d_grid` in TensorFlow, `torch.nn.functional.interpolate` in PyTorch). See an example [here](https://github.com/YyzHarry/SimPer/blob/main/src/augmentation.py#L188).
